from __future__ import annotations

PYTHINKER_CODE_PLATFORM_ID = "pythinker-code"
OPENAI_API_PLATFORM_ID = "openai"
OPENAI_CHATGPT_PLATFORM_ID = "openai-chatgpt"
OPENCODE_GO_PLATFORM_ID = "opencode-go"
MINIMAX_PLATFORM_ID = "minimax"
DEEPSEEK_PLATFORM_ID = "deepseek"
ANTHROPIC_PLATFORM_ID = "anthropic"
OPENROUTER_PLATFORM_ID = "openrouter"
LM_STUDIO_PLATFORM_ID = "lm-studio"
OLLAMA_PLATFORM_ID = "ollama"

__all__ = [
    "ANTHROPIC_PLATFORM_ID",
    "DEEPSEEK_PLATFORM_ID",
    "LM_STUDIO_PLATFORM_ID",
    "MINIMAX_PLATFORM_ID",
    "OLLAMA_PLATFORM_ID",
    "OPENAI_API_PLATFORM_ID",
    "OPENAI_CHATGPT_PLATFORM_ID",
    "OPENCODE_GO_PLATFORM_ID",
    "OPENROUTER_PLATFORM_ID",
    "PYTHINKER_CODE_PLATFORM_ID",
]
