blank_issues_enabled: true
contact_links:
  - name: Questions and General Discussion
    url: https://github.com/mohamed-elkholy95/Pythinker-Code/discussions
    about: Have questions? Welcome to open a discussion!
